---
- name: Include system setup tasks
  ansible.builtin.include_tasks:
    file: system.yml
    apply:
      tags: [system]
  tags: [always]

- name: Setup traefik
  ansible.builtin.include_tasks:
    file: traefik.yml
    apply:
      tags: [traefik]
  tags: [always]

- name: Include prometheus tasks
  ansible.builtin.include_tasks:
    file: prometheus.yml
    apply:
      tags: [prometheus]
  tags: [always]
